[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/chart"
  to = "https://james-project.onrender.com/api/chart"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "https://aimarketanalyzer.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Accept, Authorization"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for Telegram login
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self' https://oauth.telegram.org;"
    Referrer-Policy = "strict-origin-when-cross-origin"
